collections:
  - name: community.general
    version: 11.4.1
  - name: ansible.posix
    version: 2.1.0

roles:
  - src: geerlingguy.postgresql
    version: 4.0.2
  - src: nginxinc.nginx
    version: 0.25.0
